# Generated by Django 2.1.7 on 2019-02-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_bot', '0003_auto_20190220_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ni',
            unique_together={('text', 'user_id', 'chat_id')},
        ),
    ]
