# Generated by Django 2.1.7 on 2019-02-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_bot', '0004_auto_20190220_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ni',
            unique_together={('text', 'chat_id')},
        ),
    ]
