version: '3'

services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: nini_echo_bot

  django:
    build: ..
    restart: always
    volumes:
      - django_log:/usr/src/app/log
      - django_media:/usr/src/app/media
      - django_static:/usr/src/app/assets
    environment:
      ALLOWED_HOSTS: $ALLOWED_HOSTS
      DATABASE_URL: $DATABASE_URL
      DEBUG: $DEBUG
      MODE: $MODE
      SECRET_KEY: $SECRET_KEY
      LOG_SQL: $LOG_SQL
      TG_TOKEN: $TG_TOKEN
    depends_on:
      - db

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - django_media:/usr/src/app/media
      - django_static:/usr/src/app/assets
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8088:80
    depends_on:
      - django

volumes:
  pg_data:
  django_log:
  django_media:
  django_static:
