version: '3'

services:
  django:
    image: docker.arthurc.me/nini-echo-bot/server:${DOCKER_TAG}
    restart: always
    volumes:
      - django_log:/src/log
      - django_media:/src/media
      - django_static:/src/assets
    environment:
      ALLOWED_HOSTS: $ALLOWED_HOSTS
      DATABASE_URL: $DATABASE_URL
      DEBUG: $DEBUG
      MODE: $MODE
      SECRET_KEY: $SECRET_KEY
      LOG_SQL: $LOG_SQL
      TG_TOKEN: $TG_TOKEN
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOMAIN}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.redirect.entryPoint=https"
    networks:
      - web

volumes:
  django_log:
  django_media:
  django_static:

networks:
  web:
    external: true
