version: '3'

services:
  django:
    build: ..
    restart: always
    volumes:
      - django_log:/usr/src/app/log
      - django_media:/usr/src/app/media
      - django_static:/usr/src/app/assets
    environment:
      ALLOWED_HOSTS: $ALLOWED_HOSTS
      DATABASE_URL: $DATABASE_URL
      DEBUG: $DEBUG
      MODE: $MODE
      SECRET_KEY: $SECRET_KEY
      LOG_SQL: $LOG_SQL
      TG_TOKEN: $TG_TOKEN
    networks:
      - internal

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - django_media:/usr/src/app/media
      - django_static:/usr/src/app/assets
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nini.arthurc.me"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.redirect.entryPoint=https"
    networks:
      - web
      - internal
    depends_on:
      - django

volumes:
  django_log:
  django_media:
  django_static:

networks:
  web:
    external: true
  internal:
    external: false
